### PR TITLE
Update to 1.5.0

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by jsuchome** [comment]
I _think_ we've agreed on using `master` branch for 2.1 ... at least that's described at some confluence page. Of course we can change it.

I also wanted to ask - how did you come up with the changes? Did you took upstream 1.5.0 code and merged it with out previous modifications?

**Comment by stefannica** [comment]
@dirkmueller yes, as @jsuchome mentioned, please use the master branch for the most recent minor Harbor release. This is documented here: https://confluence.suse.com/display/ENGCTNRSTORY/Private+Registry+CI+CD+Pipeline#PrivateRegistryCICDPipeline-GitHubrepositorysetup

**Comment by stefannica** [comment]
Just a word of caution: we stopped maintaining the master branch via back/forward-ports about a month ago. I see this PR is based on the release-2.0 branch, which is great, except we need the exact contents of your release-2.1 branch to replace whatever is in master now.

**Comment by dirkmueller** [comment]
> I also wanted to ask - how did you come up with the changes? Did you took upstream 1.5.0 code and merged it with out previous modifications?

Yes, I did a diff of upstream 1.4.8 helm chart vs our helm chart (which was around 20k), cleaned it by deleted / added files, and applied the remaining diff (which was around 3kb) on this newer version. it applied mostly fine except for 3 places, that were easy to resolve.

**Comment by jsuchome** [comment]
I was thinking it might be better to take upstream 1.5.0 version first and then cherry-pick commits with our changes (from 2.0 branch). That way we at least have some history there...

**Comment by dirkmueller** [comment]
@jsuchome sure, can do that. personally I think its just easier to keep our patch as a single patch that we rebase within the package. thats why I suggested in the friday meeting (you were out, sorry) to have a discussion on this when stefan is back. I don't see a lot of value in the 5 levels of helm chart layering that we do (SUSE/registry/master -> SUSE/registry/release-2.x -> Devel:Registry: -> SUSE:registry -> github/SUSE/kubernetes-charts.suse.com/ ). all for that for 3kb of easy to carry local patch (which will further reduce once flavio has upstreamed the helm test support)

**Comment by dirkmueller** [comment]
we'll stop maintaining helm charts in git going forward.

**Pull request closed without merging**
